# Generated by Django 4.2.6 on 2024-11-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(related_name='user_playlists', to='movies.playlist'),
        ),
    ]
