# Generated by Django 4.2.6 on 2024-11-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
