# Generated by Django 4.2.6 on 2024-11-22 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_actors_remove_movie_directors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='actorID',
            new_name='actor_id',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='directorID',
            new_name='director_id',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genreID',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movieID',
            new_name='movie_id',
        ),
    ]
